version: '3.9'

volumes:
  data:

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: "password"
      - MYSQL_USER: "potencial"
      - MYSQL_PASSWORD: "potencial"
      - MYSQL_DATABASE: "potencial"

  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
