version: '3.7'

volumes:
  crud_volume:
    driver: local

networks:
  net_crud:
    driver: bridge

services:
    crud_db:
        image: "mysql:latest"
        container_name: crud_db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - crud_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: potencial
            MYSQL_PASSWORD: potencial
            MYSQL_USER: potencial
        networks:
            - net_crud

    crud_frontend:
        container_name: crud_frontend
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - crud_db
        expose:
            - "8000"
        ports:
            - "8000:8000"
        working_dir: /home/potencial
        networks:
            - net_crud
