version: '3.7'

volumes:
  data:

networks:
  rede:
    driver: bridge

services:
  db:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: potencial
      MYSQL_PASSWORD: potencial
      MYSQL_DATABASE: potencial
    networks:
      - rede
